version: '3'
services:
    springapp:
         image: somanathdocker/spring-boot-mongo:latest
         depends_on:
         - mongo
         ports:
         - 8080:8080
         environment:
         - MONGO_DB_HOSTNAME=mongo
         - MONGO_DB_USERNAME=devdb
         - MONGO_DB_PASSWORD=devdb@123
         networks:
         - springappnetwork
    mongo:
      image: mongo
      environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@123
      volumes:
      - mongodbebsvol:/data/db
      networks:
      - springappnetwork
volumes:
 mongodbebsvol:
   external: true
networks:
  springappnetwork:
   external: true
